name: flutter_example
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  neopop: ^1.0.2
  marquee: 2.2.3
  event_bus: 2.0.0
  google_fonts: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
